version: '3'

tasks:
  hello:
    desc: Initial task for setup
    cmds:
      - echo "Successfully installed Taskfile"
  # INFRA TASKS
  sync:
    desc: Syncs uv artifacts
    cmds:
      - uv sync
  download-data:
    desc: Downloads and saves all datasets locally
    deps: [sync]
    cmds:
      - uv run python src/02807_project/data_loader.py
  clean-data:
    desc: Cleans the downloaded datasets by removing nulls, invalid ratings, and mapping review scores
    cmds:
      - uv run python src/02807_project/data_cleaner.py
  explore-data:
    desc: Explores both raw and cleaned datasets with statistics and descriptions
    cmds:
      - uv run python src/02807_project/explore_data.py --version both
  explore-data-raw:
    desc: Explores only the raw datasets with statistics and descriptions
    cmds:
      - uv run python src/02807_project/explore_data.py --version raw
  explore-data-clean:
    desc: Explores only the cleaned datasets with statistics and descriptions
    cmds:
      - uv run python src/02807_project/explore_data.py --version clean
