version: '3'

tasks:
  hello:
    desc: Initial task for setup
    cmds:
      - echo "Successfully installed Taskfile"
  # INFRA TASKS
  sync:
    desc: Syncs uv artifacts
    cmds:
      - uv sync
  download-data:
    desc: Downloads and saves all datasets locally
    deps: [sync]
    cmds:
      - uv run python src/02807_project/data_loader.py
  clean-data:
    desc: Cleans the downloaded datasets by removing nulls, invalid ratings, and mapping review scores. Also cleans scraped Rotten Tomatoes movie details.
    cmds:
      - uv run python src/02807_project/data_cleaner.py
  scrape-rt-movies:
    desc: Scrapes Rotten Tomatoes movie titles and descriptions from unique movie IDs
    cmds:
      - uv run python src/02807_project/scrape_rt_movies.py
  retry-failed-scrapes:
    desc: Retries scraping movies that previously failed
    cmds:
      - uv run python src/02807_project/scrape_rt_movies.py --retry-failed
  merge-data:
    desc: Merges all cleaned datasets into a single comprehensive dataset using normalized movie titles
    cmds:
      - uv run python src/02807_project/merge_datasets.py
  analyze-actor-network:
    desc: Analyzes movie network based on shared actors using Girvan-Newman, Louvain, and Spectral Clustering
    cmds:
      - uv run python src/02807_project/analyze_actor_network.py
  setup-data:
    desc: Complete data setup - syncs dependencies, downloads datasets, and cleans the data
    deps: [sync]
    cmds:
      - task download-data
      - task clean-data
      - task merge-data
  explore-data:
    desc: Explores both raw and cleaned datasets with statistics and descriptions
    cmds:
      - uv run python src/02807_project/explore_data.py --version both
  explore-data-raw:
    desc: Explores only the raw datasets with statistics and descriptions
    cmds:
      - uv run python src/02807_project/explore_data.py --version raw
  explore-data-clean:
    desc: Explores only the cleaned datasets with statistics and descriptions
    cmds:
      - uv run python src/02807_project/explore_data.py --version clean
  run-frequent-items:
    desc: Run frequent itemsets analysis (use -- to pass args, e.g., -- --min-support 0.15)
    cmds:
      - uv run python src/02807_project/frequent_items.py {{.CLI_ARGS}}
  run-collaborative-filtering:
    desc: Run collaborative filtering on merged dataset (pass args after --)
    cmds:
      - uv run python src/02807_project/collaborative_filtering.py {{.CLI_ARGS}}
  run-visualize-similarities:
    desc: Run visualization of movie similarities (pass args after --)
    cmds:
      - uv run python src/02807_project/visualize_similarities.py {{.CLI_ARGS}}
