version: '3'

tasks:
  hello:
    desc: Initial task for setup
    cmds:
      - echo "Successfully installed Taskfile"
  # INFRA TASKS
  sync:
    desc: Syncs uv artifacts
    cmds:
      - uv sync
  download-data:
    desc: Downloads and saves all datasets locally
    deps: [sync]
    cmds:
      - uv run python src/02807_project/data_loader.py
  explore-data:
    desc: Explores the downloaded datasets with statistics and descriptions
    cmds:
      - uv run python src/02807_project/explore_data.py
